<div style="padding:30px; color: white; background-color: #0071CD">
<center>
<img src="img/logoub.jpeg"></img>
<center>
<h1>Algorísmica Avançada</h1>
<h2>Problemes 6 - Programació Dinàmica</h2>
</center>
</div>

In [220]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

# Programació dinàmica vs Recursió

Quan tenim un algorisme recursiu que crida múltiples vegades el mateix subproblema, cal veure si hi ha la possibilitat de convertir-ho en un algorisme de programació dinàmica. El cas de <b>Fibonacci</b> és un clar exemple ja que per a calcular el fibonacci d'un número en concret cal haver calculat el fibonnaci dels seus dos números anteriors.

Al fer-ho recursivament estarem generant el següent arbre de crides:

<img src="img/fibonacci.png">

Com podeu observar, moltes de les crides que fem ens les podem estalviar doncs amb calcular un sol cop el fibonacci de cada nombre en tenim suficient. La programació dinàmica ens ajuda en aquest cas.

<div class="alert alert-success">
    <h1>Problema 1.1: Fibonacci recursiu</h1>
    <p>
        Implementeu la funció <b>fib_rec</b>. Donat un nombre enter positiu o zero, $n$, ha de retornar el nombre de fibonacci, $F(n)$ que li correspon. <br>
        Per exemple: <br>
        $$F(0)=0, \quad F(1)=1, \quad F(2)=1, \quad F(3)=2, \quad F(4)=3, \quad F(5)=5$$
    <p>
    <p><b>Quina és la complexitat de l'algorisme? (Observeu l'arbre de la imatge anterior)</b></p>
    
</div>

In [221]:
def fib_rec(n):
    """
    Calcula el nombre amb índex 'n' de la seqüència de Fibonacci.
    
    Params
    ======
    :n: El nombre de fibonacci que volem calcular.
    
    Returns
    =======
    :F(n): El nombre de la seqüència corresponent.
    """
    if n == 0 or n == 1: return n
    return fib_rec(n-1) + fib_rec(n-2)

In [222]:
print([fib_rec(n) for n in range(20)])

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181]


<div class="alert alert-success">
    <h1>Problema 1.2: Fibonacci amb programació dinàmica (Top-Down)</h1>
    <p>
        Implementeu la funció <b>fib_top_down</b>. Seguiu una estratègia de programació dinàmica utilitzant el mateix esquema que fibonacci recursiu però on aneu emmagatzemant els càlculs realitzats prèviament.
    <p>    
</div>

In [223]:
def fib_top_down(n, dp=None):
    """
    Calcula el nombre amb índex 'n' de la seqüència de Fibonacci.
    
    Params
    ======
    :n: El nombre de fibonacci que volem calcular.
    
    Returns
    =======
    :F(n): El nombre de la seqüència corresponent.
    """
    
    # Inicialització
    if dp is None:
        dp = [0]*(n+1)
    
    # EL TEU CODI AQUÍ

    if n == 0 or n == 1: return n
    if dp[n]:
        return dp[n]
    
    else:
        dp[n] = fib_top_down(n-1, dp) + fib_top_down(n-2, dp)
        return dp[n]

In [224]:
print([fib_top_down(n) for n in range(20)])

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181]


<div class="alert alert-success">
    <h1>Problema 1.2: Fibonacci amb programació dinàmica (Bottom-Up)</h1>
    <p>
        Implementeu la funció <b>fib_bottom_up</b>. Seguiu una estratègia de programació dinàmica on aneu emmagatzemant càlculs realitzats prèviament.<br><br> 
        <b>Quina és la complexitat de l'algorisme?</b>
    <p>
        
        
    
</div>

In [225]:
def fib_bottom_up(n):
    """
    Calcula el nombre amb índex 'n' de la seqüència de Fibonacci.
    
    Params
    ======
    :n: El nombre de fibonacci que volem calcular.
    
    Returns
    =======
    :F(n): El nombre de la seqüència corresponent.
    """
    
    dp = [0]*(n+1)
    
    # EL TEU CODI AQUÍ

    if n == 0 or n == 1: return n
    
    dp[0] = 0
    dp[1] = 1
    for i in range(2, n+1):
        dp[i] = dp[i-1] + dp[i-2]
    return dp[n]

In [226]:
print([fib_bottom_up(n) for n in range(20)])

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181]


 <div class="alert alert-success">
     <h1>Problema 2: Rod Cutting</h1>  
     <p>Volem tallar una barra de N segments de longitud en trossos per maximitzar-ne el seu valor de venta. Cada segment tallat té un preu associat en funció de la seva longitud.<br>
     <center><img src='https://iq.opengenus.org/content/images/2020/01/07-rodcutting-example-2.jpg' width='50%'></center>
     Per exemple, donada una barra de 5 peces de longitud i la taula de preus següent: <br><br>
     Long: 1 2 3 4 5<br>
     Preu: 1 5 5 6 7<br><br>
     Podem decidir
     <ul>
         <li>no tallar la barra, long=5 i per tant preu=7.
         <li>Tallar-la en dos trossos de 1 i 4 i per tant preu=1+6=7
         <li>Tallar-la en cinc trossos de 1 i per tant preu=5
         <li>...
    </ul>             
    </p>
 </div>

In [227]:
def rod_cutting_rec(N, prices):
    """
    Algorisme recursiu.
    
    Params
    ======
    :N: Un enter amb el nombre de segments de la barra
    :prices: Una llista amb els preus de cada longitud de segment.
    
    Returns
    =======
    :best: El millor preu de venta de les peces
    """
    
    best = 0
    
    # EL TEU CODI AQUÍ
    if N == 0: return 0

    for i in range(N):
        # Hace falta hacer el ajuste. cada vez consideramos una barra de longitud n, donde vamos restando i+1 piezas.
        best = max(rod_cutting_rec(N-i-1, prices) + prices[i], best)

    return best

In [228]:
rod_cutting_rec(5, [1,5,5,6,7]) # Retorna 11

11

In [229]:
def rod_cutting_dp_bottom_up(N, prices):
    """
    Algorisme programació dinàmica bottom up.
    
    Params
    ======
    :N: Un enter amb el nombre de segments de la barra
    :prices: Una llista amb els preus de cada longitud de segment.
    
    Returns
    =======
    :best: El millor preu de venta de les peces
    """
    
    best = 0
    
    # EL TEU CODI AQUÍ
    dp = [0] * (N+1)

    for i in range(N+1):
        if i == 0 or i == 1: 
            dp[i] = i
            continue

        else:
            for j in range(i):
                dp[i] = max(dp[i], dp[j] + prices[i-j-1])


    best = dp[N]
    

    return best

In [230]:
rod_cutting_dp_bottom_up(5,[1,5,5,6,7]) # Retorna 11

11

In [231]:
def rod_cutting_dp_top_down(N, prices, dp=None):
    """
    Algorisme programació dinàmica top down.
    
    Params
    ======
    :N: Un enter amb el nombre de segments de la barra
    :prices: Una llista amb els preus de cada longitud de segment.
    
    Returns
    =======
    :best: El millor preu de venta de les peces
    """
    
    best = 0
    
    # EL TEU CODI AQUÍ

    if dp == None:
        dp = [0] * (N+1)
        

    if N == 0: return 0
    if dp[N]: return dp[N]
    maximo = -1
    for i in range(N):
        # Hace falta hacer el ajuste. cada vez consideramos una barra de longitud n, donde vamos restando i+1 piezas.
        maximo = max(maximo, 
                     rod_cutting_dp_top_down(N-i-1, prices, dp) + prices[i], dp[i])

    dp[N] = maximo
    best = dp[N]
    return best

In [232]:
rod_cutting_dp_top_down(5, [1,5,5,6,7]) # Retorna 11

11

<div class="alert alert-success">
    <h1>Problema 3: Subseqüència Incremental més Llarga (Longest Increasing Subsequence, LIS)</h1>
    <p>
        Donada una seqüència de números, per exemple: $10, 22, 9, 33, 21, 50, 41, 60, 80$, volem trobar la subsequència d'elements més llarga possible que satisfaci que els seus elements estiguin ordenats de petit a gran.<br>
        En el cas de l'exemple donat, la subseqüència més llarga té 6 elements: $10, 22, 33, 50, 60, 80$. Observeu però, que no és única.
    <p>
    
</div>

 <div class="alert alert-success">
     <h1>Problema 3.1: LIS Recursiva</h1>    
    <p><b>Quina complexitat té aquest algorisme?</b></p>
 </div>

In [233]:
def lis_ends_here(seq, n):
    """
    Aquesta funció ens retorna la longitud de la seqüència més llarga que acaba a la posició 'n'.
    
    Params
    ======
    :seq: Llista d'elements
    :n: Índex de la llista
    
    Returns
    =======
    :val: Longitud de la LIS suposant que finalitza a 'n'.
    """

# Si no hay una secuencia, retornamos 0.
    if seq == []: return 0
    
    # Comenzamos a comparar
    longitud = 0
    curr = seq[0]
    posibilidades = []

    for i in range(1, n):
        if seq[i] > curr: 
            longitud += 1
        else:
            posibilidades.append(lis_ends_here(seq[i:], n))

    for posibilidad in posibilidades:
        longitud = max(longitud, posibilidad)


    return longitud


print(lis_ends_here([1,2,0,9,3,5,4,6,8], 6))

def lis_rec(seq):
    """
    Solució recursiva al problema LIS.
    
    Params
    ======
    :seq: Seqüència inicial.
    
    Returns
    =======
    :val: Longitud de LIS.
    """
    pass

5


In [234]:
print(lis_rec([1,2,0,9,3,5,4,6,8]))  # Retorna 6
print(lis_rec([4,1,2,1]))            # Retorna 2

None
None


 <div class="alert alert-success">
     <h1>Problema 3.2: LIS amb Programació dinàmica</h1>    
    <p><b>Quina complexitat té aquest algorisme?</b></p>
 </div>

In [235]:
def lis_dp_bottom_up(seq):
    """
    Solució al problema LIS usant programació dinàmica.
    
    Params
    ======
    :seq: Llista d'enters
    
    Returns
    =======
    :val: La longitud de la subseqüència incremental més llarga.
    
    """
    pass

In [236]:
print(lis_dp_bottom_up([1,2,0,9,3,5,4,6,8])) # Retorna 6
print(lis_dp_bottom_up([4,1,2,1]))           # Retorna 2

None
None


 <div class="alert alert-success">
    <h1>Problema 4: Levensthein</h1>    
    <p>Donades dues paraules $A$ i $B$ volem trobar el cost d'edició entre elles. Les operacions que es permeten són:</p>
    <ol>
        <li> <b>Inserir</b> una lletra en qualsevol posició de la paraula. Per exemple, podem transformar la paraula TACA en la paraula TRACA amb només una operació d'inserció.
        <li> <b>Eliminar</b> una lletra en qualsevol posició de la paraula. Per exemple, podem transformar la paraula TRACA en la paraula TACA amb només una operació d'eliminació.
        <li> <b>Substituir</b> una lletra per una altra. Per exemple, podem transformar la paraula TACA en la paraula TOCA amb només una operació de substitució.
  </ol>
    <p>Implementeu un algorisme de programació dinàmica que ens permeti trobar el cost mínim d'edició entre les dues paraules i que també retorni les operacions que s'han de fer per transformar una paraula en l'altre. <br>
        Per exemple, l'execució de<br> <b>levensthein('WINE', 'WAITER')</b> ha d'imprimir:<br><br>
        <code>COST: 3
[0, 1, 2, 3, 4, 5, 6]
[1, 0, 1, 2, 3, 4, 5]
[2, 1, 1, 1, 2, 3, 4]
[3, 2, 2, 2, 2, 3, 4]
[4, 3, 3, 3, 3, 2, 3]
MAN W W  # Ja que estem 'mantenint la lletra W entre les paraules
INS   A  # Ja que estem 'inserint' la lletra A enmig de la paraula
MAN I I 
SUB N T  # Ja que estem 'substituint' la lletra N per la T
MAN E E
INS   R
         # En el cas d'eliminar, podeu imprimir DEL</code>
    </p>
    
 </div>

In [ ]:
import numpy as np

def levensthein(word_B, word_A, del_cost = 1, ins_cost = 1, sub_cost = 1):    
    """
    Algorisme de levensthein.
    
    Params
    ======
    :word_A, word_B: Les dues paraules a comparar
    :del_cost, ins_cost, sub_cost: Els costos d'eliminar, inserir i substituir, respectivament.
    
    Returns
    =======
    :cost: El cost d'edició entre les paraules
    """

    len_B = len(word_B)
    len_A = len(word_A)

    lev = np.zeros((len_B+1, len_A+1), dtype=int)
    for i in range(len_B+1):
        lev[i][0] = i # Rellenamos la primera fila.
    for i in range(len_A+1):
        lev[0][i] = i # Y la primera columna.

    # Rellenamos todo Levenshtein.
    for i in range (1, len_B+1):
        for j in range(1, len_A+1):
            lev[i][j] = min( 
                lev[i]  [j-1] + del_cost,
                lev[i-1][j]   + ins_cost,
                lev[i-1][j-1] + (sub_cost if word_B[i-1] != word_A[j-1] else 0)
            )

    # Hagamos el backtracing.
    rec = []
    i = 0
    j = 0

    while i < len_B or j < len_A:
        
        if lev[i][j] == lev[i+1][j+1]: # Mantenemos
            rec.append(f"MAN: {word_A[j]} {word_B[i]} ")
            i +=1
            j +=1

        else:
            # Tenemos que ver cuál es el mínimo entre añadir, sustraer y sustituir.

            # Caso en el que sustituir es mejor o igual.
            if lev[i+1][j+1] <= lev[i+1][j] or lev[i+1][j+1] <= lev[i][j+1]:
                rec.append(f"SUB: {word_B[i]} {word_A[j]}")
                i +=1
                j +=1

            if lev[i+1][j] < lev[i][j+1]:
                rec.append(f"DEL: {word_B[i]} ")
                i +=1

            else:
                rec.append(f"INS: {word_A[j]}")
                j +=1



    print(f"COST {lev[len_B][len_A]}")
    print(lev)
    for elem in rec:
        print(elem)
    
    pass

levensthein('WINE', 'WAITER') 

COST 3
[[0 1 2 3 4 5 6]
 [1 0 1 2 3 4 5]
 [2 1 1 1 2 3 4]
 [3 2 2 2 2 3 4]
 [4 3 3 3 3 2 3]]
MAN: W W
SUB: I A
INS: I
SUB: N T
INS: E
MAN: E R


In [238]:
levensthein('WINE', 'WAITER') 
# COST 3
# [0, 1, 2, 3, 4, 5, 6]
# [1, 0, 1, 2, 3, 4, 5]
# [2, 1, 1, 1, 2, 3, 4]
# [3, 2, 2, 2, 2, 3, 4]
# [4, 3, 3, 3, 3, 2, 3]
# MAN: W W
# SUB: A I
# INS: I  
# SUB: T N
# SUB: E E
# INS: R  

COST 3
[[0 1 2 3 4 5 6]
 [1 0 1 2 3 4 5]
 [2 1 1 1 2 3 4]
 [3 2 2 2 2 3 4]
 [4 3 3 3 3 2 3]]
MAN: W W
SUB: I A
INS: T
SUB: N T
INS: R
MAN: E R


In [239]:
levensthein('INDUSTRY', 'INTEREST', sub_cost=5) 
# COST 8
# [0, 1, 2, 3, 4, 5, 6, 7, 8]
# [1, 0, 1, 2, 3, 4, 5, 6, 7]
# [2, 1, 0, 1, 2, 3, 4, 5, 6]
# [3, 2, 1, 2, 3, 4, 5, 6, 7]
# [4, 3, 2, 3, 4, 5, 6, 7, 8]
# [5, 4, 3, 4, 5, 6, 7, 6, 7]
# [6, 5, 4, 3, 4, 5, 6, 7, 6]
# [7, 6, 5, 4, 5, 4, 5, 6, 7]
# [8, 7, 6, 5, 6, 5, 6, 7, 8]
# MAN: I I
# MAN: N N
# INS:   T
# INS:   E
# INS:   R
# INS:   E
# DEL: D  
# DEL: U  
# MAN: S S
# MAN: T T
# DEL: R  
# DEL: Y  

IndexError: string index out of range

 <div class="alert alert-success">
     <h1>Problema 5: Cent Savings</h1>    
    <p>Volem agrupar un conjunt de preus ordenats en, com a màxim, $d+1$ grups. Cada grup de preus es suma i s'arrodoneix a la desena més propera (0, 10, 20,...). L'objectiu és trobar el mínim preu possible donada una llista i un enter $d$. Per formar els grups es talla la llista per la posició que es vulgui sense canviar-ne l'ordre.
    <ul>
    <li>Exemple1: Donada la llista $[13, 14]$ i $d=1$, el valor òptim és $20$ que consisteix en fer $2$ grups: $10+10$.
    <li>Exemple2: Donada la llista $[12,15,19]$ i $d=2$, el valor òptim és 40 fent 2 grups (i no 3 que seria el màxim possible). $Grup(12)=10 + Grup(15,19)=30$
    </ul>
    </p>
 </div>

<div class="alert alert-info">
Si us animeu, podeu penjar la solució a la plataforma <a href="https://open.kattis.com/problems/centsavings">KATTIS</a>. <br>Heu de seleccionar Python3 com a llenguatge i fer servir el format:
</div>

```python
n, d = input().split()
n, d = int(n), int(d)
lst = [int(a) for a in input().split()]

def cent_savings(lst, d):
    # El teu codi aquí

print(f'{cent_savings(lst, d)}')
```

In [ ]:
def myround(val):
    """
    Funció auxiliar per arrodonir correctament segons l'enunciat.
    """
    if val%5==0:
        val = val+1
    return round(val, -1)

def cent_savings_rec(lst, d):
    """
    Algorisme recursiu.
    
    Params
    ======
    :lst: Una llista de preus 
    :d: El nombre de talls que podem fer (grups-1)
    
    Returns
    =======
    :minimal: El preu més baix assolible
    """
    pass

In [ ]:
cent_savings_rec([12,15,19], 2) # Retorna 40

In [ ]:
def cent_savings_dp_top_down(lst, d, memo={}):  
    """
    Algorisme programació dinàmica top down.
    
    Params
    ======
    :lst: Una llista de preus 
    :d: El nombre de talls que podem fer (grups-1)
    :memo: Un diccionari de memòria.
    
    Returns
    =======
    :minimal: El preu més baix assolible
    """
    
    pass

In [ ]:
cent_savings_dp_top_down([12,15,19], 2) # Retorna 40

In [ ]:
def cent_savings_dp_bottom_up(lst, d):
    """
    Algorisme programació dinàmica bottom up.
    
    Params
    ======
    :lst: Una llista de preus 
    :d: El nombre de talls que podem fer (grups-1)
    
    Returns
    =======
    :minimal: El preu més baix assolible
    """
    
    pass

In [ ]:
cent_savings_dp_bottom_up([12,15,19], 2) # Retorna 40